# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_slug',
            field=models.SlugField(default=-32, max_length=250),
            preserve_default=False,
        ),
    ]
